begin;
insert into public.explore_destinations
  (id, name, country, continent, types, description_es, cover_query, featured, sort_order, published)
values
('lisboa', 'Lisboa', 'Portugal', 'Europa', ARRAY['cultural', 'gastro']::text[], 'Capital portuguesa de colinas, tranvías amarillos y azulejos. Famosa por sus miradores, su pastel de nata, la melancolía del fado y un casco antiguo que parece sacado de otra época.', 'Lisbon Portugal tram Alfama', true, 0, true),
('madrid', 'Madrid', 'España', 'Europa', ARRAY['cultural', 'gastro']::text[], 'Museos de primera, tapas hasta la madrugada y una energía que no se apaga. Del Prado al Retiro, Madrid mezcla lo castizo con lo cosmopolita sin despeinarse.', 'Madrid Gran Via skyline', false, 1, true),
('paris', 'París', 'Francia', 'Europa', ARRAY['cultural', 'gastro']::text[], 'La ciudad de la luz no necesita presentación: bulevares elegantes, cafés con historia y un museo en cada esquina. Perderse por Montmartre sigue siendo un plan perfecto.', 'Paris Eiffel Tower sunset', false, 2, true),
('roma', 'Roma', 'Italia', 'Europa', ARRAY['cultural', 'gastro']::text[], 'Un museo al aire libre donde cada plaza esconde dos mil años de historia. Entre ruinas imperiales y trattorias, Roma se recorre despacio y con gelato en mano.', 'Rome Colosseum italy', false, 3, true),
('praga', 'Praga', 'Chequia', 'Europa', ARRAY['cultural']::text[], 'Torres góticas, callejones empedrados y el Moldava atravesándolo todo. Praga parece diseñada para caminarla de noche, cuando el Puente de Carlos se queda casi vacío.', 'Prague Charles Bridge old town', false, 4, true),
('amsterdam', 'Ámsterdam', 'Países Bajos', 'Europa', ARRAY['cultural', 'relax']::text[], 'Canales, bicicletas y casas inclinadas que parecen apoyarse unas en otras. Una ciudad compacta donde los museos de primera conviven con mercados flotantes de flores.', 'Amsterdam canals houses bikes', false, 5, true),
('reikiavik', 'Reikiavik', 'Islandia', 'Europa', ARRAY['aventura', 'relax']::text[], 'Puerta de entrada a un país de volcanes, glaciares y auroras boreales. La capital más al norte del mundo combina piscinas geotermales con una escena creativa sorprendente.', 'Reykjavik Iceland Hallgrimskirkja', false, 6, true),
('atenas', 'Atenas', 'Grecia', 'Europa', ARRAY['cultural', 'gastro']::text[], 'La cuna de la civilización occidental sigue latiendo bajo la Acrópolis. Barrios como Plaka o Monastiraki mezclan ruinas, tabernas y un caos encantador.', 'Athens Acropolis Parthenon', false, 7, true),
('santorini', 'Santorini', 'Grecia', 'Europa', ARRAY['relax']::text[], 'Casas blancas colgadas sobre una caldera volcánica y los atardeceres más fotografiados del Egeo. El destino de postal por excelencia, con calas de arena negra incluidas.', 'Santorini Oia blue domes sunset', false, 8, true),
('estambul', 'Estambul', 'Turquía', 'Europa', ARRAY['cultural', 'gastro']::text[], 'La única ciudad del mundo a caballo entre dos continentes. Mezquitas monumentales, bazares infinitos y el Bósforo como telón de fondo de un choque cultural fascinante.', 'Istanbul Hagia Sophia Bosphorus', false, 9, true),
('tokio', 'Tokio', 'Japón', 'Asia', ARRAY['cultural', 'gastro']::text[], 'Neones, templos y la mayor concentración de estrellas Michelin del planeta. Tokio es muchas ciudades a la vez: caótica en Shibuya, serena en Yanaka, futurista en Odaiba.', 'Tokyo Shibuya crossing night', false, 10, true),
('kioto', 'Kioto', 'Japón', 'Asia', ARRAY['cultural', 'relax']::text[], 'Mil templos, jardines zen y geishas cruzando callejones de madera. La antigua capital imperial es el Japón que imaginabas antes de ir a Japón.', 'Kyoto Fushimi Inari torii gates', true, 11, true),
('bali', 'Bali', 'Indonesia', 'Asia', ARRAY['relax', 'aventura']::text[], 'Arrozales en terraza, templos entre la jungla y playas para todos los gustos. La isla de los dioses combina espiritualidad, surf y una hospitalidad legendaria.', 'Bali rice terraces temple', false, 12, true),
('bangkok', 'Bangkok', 'Tailandia', 'Asia', ARRAY['gastro', 'cultural']::text[], 'Templos dorados, mercados flotantes y la mejor comida callejera del mundo. Bangkok abruma al principio y engancha después: es puro movimiento.', 'Bangkok Wat Arun temple', false, 13, true),
('hanoi', 'Hanói', 'Vietnam', 'Asia', ARRAY['cultural', 'gastro']::text[], 'Motos por miles, pho humeante en cada esquina y un casco antiguo de 36 calles gremiales. La puerta de entrada perfecta a la bahía de Halong.', 'Hanoi Vietnam old quarter street', false, 14, true),
('seul', 'Seúl', 'Corea del Sur', 'Asia', ARRAY['cultural', 'gastro']::text[], 'Palacios de la dinastía Joseon junto a rascacielos y barrios de moda que marcan tendencia mundial. El K-everything tiene su capital aquí, y se come de maravilla.', 'Seoul Gyeongbokgung palace skyline', false, 15, true),
('singapur', 'Singapur', 'Singapur', 'Asia', ARRAY['gastro', 'relax']::text[], 'La ciudad-jardín donde la comida de hawker vale una estrella Michelin. Futurista, verde e impecable: el escenario de Gardens by the Bay parece de otro planeta.', 'Singapore Marina Bay Gardens', false, 16, true),
('dubai', 'Dubái', 'Emiratos Árabes', 'Asia', ARRAY['relax', 'aventura']::text[], 'Rascacielos imposibles levantados sobre el desierto. Entre el zoco del oro y el edificio más alto del mundo, Dubái es exceso puro — y safaris de dunas al atardecer.', 'Dubai Burj Khalifa skyline desert', false, 17, true),
('nueva-york', 'Nueva York', 'EEUU', 'América', ARRAY['cultural', 'gastro']::text[], 'La ciudad que nunca duerme cumple todos los tópicos y aun así sorprende. Museos gigantes, barrios con personalidad propia y una energía que no existe en ningún otro sitio.', 'New York Manhattan skyline', false, 18, true),
('cusco', 'Cusco', 'Perú', 'América', ARRAY['cultural', 'aventura']::text[], 'La antigua capital del imperio inca, a 3.400 metros de altura, es la base para llegar a Machu Picchu. Muros incas, iglesias coloniales y el Valle Sagrado a un paso.', 'Cusco Peru plaza de armas', true, 19, true),
('buenos-aires', 'Buenos Aires', 'Argentina', 'América', ARRAY['cultural', 'gastro']::text[], 'Tango, parrillas y librerías en teatros centenarios. La ciudad más europea de Sudamérica tiene barrios que son mundos: San Telmo, Palermo, La Boca.', 'Buenos Aires La Boca Caminito', false, 20, true),
('rio', 'Río de Janeiro', 'Brasil', 'América', ARRAY['relax', 'aventura']::text[], 'Montañas de granito cayendo sobre playas míticas, samba en la calle y el Cristo vigilándolo todo. Pocas ciudades tienen un escenario natural así.', 'Rio de Janeiro Christ Redeemer aerial', false, 21, true),
('cdmx', 'Ciudad de México', 'México', 'América', ARRAY['cultural', 'gastro']::text[], 'Una megalópolis construida sobre una ciudad azteca, con la escena gastronómica más excitante de América. Murales, mercados y barrios como Roma o Coyoacán para perderse.', 'Mexico City Palacio Bellas Artes', false, 22, true),
('vancouver', 'Vancouver', 'Canadá', 'América', ARRAY['aventura', 'relax']::text[], 'Océano por un lado, montañas nevadas por el otro. Vancouver es la excusa urbana perfecta para una escapada de naturaleza: kayak al amanecer, esquí por la tarde.', 'Vancouver Canada skyline mountains', false, 23, true),
('la-habana', 'La Habana', 'Cuba', 'América', ARRAY['cultural', 'relax']::text[], 'Coches clásicos, fachadas coloniales desgastadas por el salitre y son cubano saliendo de cada ventana. Una ciudad detenida en el tiempo que se vive con todos los sentidos.', 'Havana Cuba classic cars colonial', false, 24, true),
('marrakech', 'Marrakech', 'Marruecos', 'África', ARRAY['cultural', 'gastro']::text[], 'Zocos laberínticos, riads escondidos tras puertas anónimas y la plaza de Jemaa el-Fna convertida en teatro cada atardecer. El desierto y el Atlas esperan a las puertas.', 'Marrakech Morocco medina souk', true, 25, true),
('el-cairo', 'El Cairo', 'Egipto', 'África', ARRAY['cultural']::text[], 'Las pirámides de Giza a las afueras, cinco mil años de historia dentro. Caótico, ruidoso y absolutamente fascinante: el Nilo lo atraviesa todo.', 'Cairo Egypt pyramids Giza', false, 26, true),
('ciudad-del-cabo', 'Ciudad del Cabo', 'Sudáfrica', 'África', ARRAY['aventura', 'relax']::text[], 'Table Mountain de fondo, pingüinos en la playa y viñedos a media hora. Pocas ciudades ofrecen tanta naturaleza espectacular sin salir del área metropolitana.', 'Cape Town Table Mountain aerial', false, 27, true),
('sidney', 'Sídney', 'Australia', 'Oceanía', ARRAY['relax', 'aventura']::text[], 'La Ópera, el puente y decenas de playas urbanas donde el surf es religión. Sídney vive de cara al mar y contagia su estilo de vida al aire libre desde el primer día.', 'Sydney Opera House harbour', true, 28, true),
('auckland', 'Auckland', 'Nueva Zelanda', 'Oceanía', ARRAY['aventura']::text[], 'La ciudad de las velas es la base perfecta para explorar la Tierra Media real: volcanes, playas negras y fiordos. Aventura en estado puro a un vuelo interno de distancia.', 'Auckland New Zealand skyline harbour', false, 29, true)
on conflict (id) do nothing;
-- Solo los 30 destinos del catálogo inicial; no publica otros borradores.
update public.explore_destinations as destination
set published = true, country_code = coalesce(destination.country_code, seed.country_code)
from (values
  ('lisboa', 'Portugal', 'PT'),
  ('madrid', 'España', 'ES'),
  ('paris', 'Francia', 'FR'),
  ('roma', 'Italia', 'IT'),
  ('praga', 'Chequia', 'CZ'),
  ('amsterdam', 'Países Bajos', 'NL'),
  ('reikiavik', 'Islandia', 'IS'),
  ('atenas', 'Grecia', 'GR'),
  ('santorini', 'Grecia', 'GR'),
  ('estambul', 'Turquía', 'TR'),
  ('tokio', 'Japón', 'JP'),
  ('kioto', 'Japón', 'JP'),
  ('bali', 'Indonesia', 'ID'),
  ('bangkok', 'Tailandia', 'TH'),
  ('hanoi', 'Vietnam', 'VN'),
  ('seul', 'Corea del Sur', 'KR'),
  ('singapur', 'Singapur', 'SG'),
  ('dubai', 'Emiratos Árabes', 'AE'),
  ('nueva-york', 'EEUU', 'US'),
  ('cusco', 'Perú', 'PE'),
  ('buenos-aires', 'Argentina', 'AR'),
  ('rio', 'Brasil', 'BR'),
  ('cdmx', 'México', 'MX'),
  ('vancouver', 'Canadá', 'CA'),
  ('la-habana', 'Cuba', 'CU'),
  ('marrakech', 'Marruecos', 'MA'),
  ('el-cairo', 'Egipto', 'EG'),
  ('ciudad-del-cabo', 'Sudáfrica', 'ZA'),
  ('sidney', 'Australia', 'AU'),
  ('auckland', 'Nueva Zelanda', 'NZ')
) as seed(id, country, country_code)
where destination.id = seed.id and destination.country = seed.country;
-- Conserva cualquier edición que ya se haya realizado en Supabase.
update public.explore_destinations as destination
set editorial_rating = coalesce(destination.editorial_rating, original.rating::numeric),
    price_range = coalesce(destination.price_range, original.price_range),
    language_code = coalesce(destination.language_code, original.language_code),
    language_label = coalesce(destination.language_label, original.language_label)
from (values
  ('lisboa', 'Portugal', '4.8', 'mid', 'PT', 'Portugués'),
  ('madrid', 'España', '4.4', 'low', 'ES', 'Español'),
  ('paris', 'Francia', '4.6', 'high', 'FR', 'Francés'),
  ('roma', 'Italia', '4.7', 'mid', 'IT', 'Italiano'),
  ('praga', 'Chequia', '4.5', 'low', 'CS', 'Checo'),
  ('amsterdam', 'Países Bajos', '4.4', 'high', 'NL', 'Neerlandés'),
  ('reikiavik', 'Islandia', '4.6', 'high', 'IS', 'Islandés'),
  ('atenas', 'Grecia', '4.3', 'low', 'EL', 'Griego'),
  ('santorini', 'Grecia', '4.7', 'high', 'EL', 'Griego'),
  ('estambul', 'Turquía', '4.6', 'low', 'TR', 'Turco'),
  ('tokio', 'Japón', '4.5', 'high', 'JA', 'Japonés'),
  ('kioto', 'Japón', '4.8', 'high', 'JA', 'Japonés'),
  ('bali', 'Indonesia', '4.7', 'mid', 'ID', 'Indonesio'),
  ('bangkok', 'Tailandia', '4.4', 'low', 'TH', 'Tailandés'),
  ('hanoi', 'Vietnam', '4.3', 'low', 'VI', 'Vietnamita'),
  ('seul', 'Corea del Sur', '4.5', 'mid', 'KO', 'Coreano'),
  ('singapur', 'Singapur', '4.4', 'high', 'EN', 'Inglés'),
  ('dubai', 'Emiratos Árabes', '4.2', 'high', 'AR', 'Árabe'),
  ('nueva-york', 'EEUU', '4.2', 'high', 'EN', 'Inglés'),
  ('cusco', 'Perú', '4.8', 'low', 'ES', 'Español'),
  ('buenos-aires', 'Argentina', '4.5', 'low', 'ES', 'Español'),
  ('rio', 'Brasil', '4.6', 'mid', 'PT', 'Portugués'),
  ('cdmx', 'México', '4.5', 'low', 'ES', 'Español'),
  ('vancouver', 'Canadá', '4.3', 'high', 'EN', 'Inglés'),
  ('la-habana', 'Cuba', '4.1', 'low', 'ES', 'Español'),
  ('marrakech', 'Marruecos', '4.4', 'low', 'AR', 'Árabe'),
  ('el-cairo', 'Egipto', '4.3', 'low', 'AR', 'Árabe'),
  ('ciudad-del-cabo', 'Sudáfrica', '4.7', 'mid', 'EN', 'Inglés'),
  ('sidney', 'Australia', '4.5', 'high', 'EN', 'Inglés'),
  ('auckland', 'Nueva Zelanda', '4.2', 'high', 'EN', 'Inglés')
) as original(id, country, rating, price_range, language_code, language_label)
where destination.id = original.id and destination.country = original.country;
commit;