export function normalizeCountryName(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
}

/** Names (es + en) → ISO 3166-1 alpha-2 */
const COUNTRY_TO_ISO: Record<string, string> = {
  // Europa
  espana: 'ES',
  spain: 'ES',
  francia: 'FR',
  france: 'FR',
  italia: 'IT',
  italy: 'IT',
  portugal: 'PT',
  alemania: 'DE',
  germany: 'DE',
  'reino unido': 'GB',
  'united kingdom': 'GB',
  irlanda: 'IE',
  ireland: 'IE',
  'paises bajos': 'NL',
  netherlands: 'NL',
  holanda: 'NL',
  belgica: 'BE',
  belgium: 'BE',
  suiza: 'CH',
  switzerland: 'CH',
  austria: 'AT',
  grecia: 'GR',
  greece: 'GR',
  croacia: 'HR',
  croatia: 'HR',
  'republica checa': 'CZ',
  chequia: 'CZ',
  'czech republic': 'CZ',
  polonia: 'PL',
  poland: 'PL',
  hungria: 'HU',
  hungary: 'HU',
  suecia: 'SE',
  sweden: 'SE',
  noruega: 'NO',
  norway: 'NO',
  dinamarca: 'DK',
  denmark: 'DK',
  finlandia: 'FI',
  finland: 'FI',
  islandia: 'IS',
  iceland: 'IS',
  turquia: 'TR',
  turkey: 'TR',
  // América
  'estados unidos': 'US',
  'united states': 'US',
  eeuu: 'US',
  usa: 'US',
  canada: 'CA',
  mexico: 'MX',
  argentina: 'AR',
  brasil: 'BR',
  brazil: 'BR',
  chile: 'CL',
  peru: 'PE',
  colombia: 'CO',
  'costa rica': 'CR',
  cuba: 'CU',
  'republica dominicana': 'DO',
  // Asia
  japon: 'JP',
  japan: 'JP',
  china: 'CN',
  'corea del sur': 'KR',
  'south korea': 'KR',
  tailandia: 'TH',
  thailand: 'TH',
  vietnam: 'VN',
  indonesia: 'ID',
  india: 'IN',
  singapur: 'SG',
  singapore: 'SG',
  malasia: 'MY',
  malaysia: 'MY',
  filipinas: 'PH',
  philippines: 'PH',
  'emiratos arabes unidos': 'AE',
  'united arab emirates': 'AE',
  israel: 'IL',
  // África
  marruecos: 'MA',
  morocco: 'MA',
  egipto: 'EG',
  egypt: 'EG',
  sudafrica: 'ZA',
  'south africa': 'ZA',
  kenia: 'KE',
  kenya: 'KE',
  tanzania: 'TZ',
  // Oceanía
  australia: 'AU',
  'nueva zelanda': 'NZ',
  'new zealand': 'NZ',
};

export function countryNameToIso(name: string): string | null {
  return COUNTRY_TO_ISO[normalizeCountryName(name)] ?? null;
}
