import type { Continent, Destination, DestinationType, PriceRange } from '@/types/destination';

export const DESTINATION_TYPE_LABELS: Record<DestinationType, string> = {
  cultural: 'Cultural',
  gastro: 'Gastronomía',
  aventura: 'Aventura',
  relax: 'Relax',
};

export const PRICE_META: Record<PriceRange, { symbol: string; label: string }> = {
  low: { symbol: '€', label: 'Bajo' },
  mid: { symbol: '€€', label: 'Medio' },
  high: { symbol: '€€€', label: 'Alto' },
};

export const CONTINENTS: Continent[] = ['Europa', 'Asia', 'América', 'África', 'Oceanía'];

export const DESTINATIONS: Destination[] = [
  // ---------- Europa ----------
  {
    id: 'lisboa',
    name: 'Lisboa',
    country: 'Portugal',
    continent: 'Europa',
    types: ['cultural', 'gastro'],
    priceRange: 'mid',
    rating: 4.8,
    description:
      'Capital portuguesa de colinas, tranvías amarillos y azulejos. Famosa por sus miradores, su pastel de nata, la melancolía del fado y un casco antiguo que parece sacado de otra época.',
    coverQuery: 'Lisbon Portugal tram Alfama',
    coordinates: { lat: 38.7223, lng: -9.1393 },
    language: { code: 'PT', label: 'Portugués' },
    featured: true,
    highlights: [
      { name: 'Torre de Belém', tag: 'Monumento', query: 'Belem Tower Lisbon' },
      { name: 'Alfama', tag: 'Barrio · Fado', query: 'Alfama Lisbon streets' },
      { name: 'Tranvía 28', tag: 'Icono', query: 'Tram 28 Lisbon yellow' },
      { name: 'LX Factory', tag: 'Ocio · Mercado', query: 'LX Factory Lisbon' },
    ],
  },
  {
    id: 'madrid',
    name: 'Madrid',
    country: 'España',
    continent: 'Europa',
    types: ['cultural', 'gastro'],
    priceRange: 'low',
    rating: 4.4,
    description:
      'Museos de primera, tapas hasta la madrugada y una energía que no se apaga. Del Prado al Retiro, Madrid mezcla lo castizo con lo cosmopolita sin despeinarse.',
    coverQuery: 'Madrid Gran Via skyline',
    coordinates: { lat: 40.4168, lng: -3.7038 },
    language: { code: 'ES', label: 'Español' },
    highlights: [
      { name: 'Museo del Prado', tag: 'Museo', query: 'Prado Museum Madrid' },
      { name: 'El Retiro', tag: 'Parque', query: 'Retiro Park Madrid' },
      { name: 'Mercado San Miguel', tag: 'Gastronomía', query: 'San Miguel Market Madrid' },
    ],
  },
  {
    id: 'paris',
    name: 'París',
    country: 'Francia',
    continent: 'Europa',
    types: ['cultural', 'gastro'],
    priceRange: 'high',
    rating: 4.6,
    description:
      'La ciudad de la luz no necesita presentación: bulevares elegantes, cafés con historia y un museo en cada esquina. Perderse por Montmartre sigue siendo un plan perfecto.',
    coverQuery: 'Paris Eiffel Tower sunset',
    coordinates: { lat: 48.8566, lng: 2.3522 },
    language: { code: 'FR', label: 'Francés' },
    highlights: [
      { name: 'Museo del Louvre', tag: 'Museo', query: 'Louvre Museum Paris pyramid' },
      { name: 'Montmartre', tag: 'Barrio · Bohemio', query: 'Montmartre Paris Sacre Coeur' },
      { name: 'Sena al atardecer', tag: 'Paseo', query: 'Seine river Paris sunset' },
    ],
  },
  {
    id: 'roma',
    name: 'Roma',
    country: 'Italia',
    continent: 'Europa',
    types: ['cultural', 'gastro'],
    priceRange: 'mid',
    rating: 4.7,
    description:
      'Un museo al aire libre donde cada plaza esconde dos mil años de historia. Entre ruinas imperiales y trattorias, Roma se recorre despacio y con gelato en mano.',
    coverQuery: 'Rome Colosseum italy',
    coordinates: { lat: 41.9028, lng: 12.4964 },
    language: { code: 'IT', label: 'Italiano' },
    highlights: [
      { name: 'Coliseo', tag: 'Monumento', query: 'Colosseum Rome' },
      { name: 'Trastevere', tag: 'Barrio · Gastro', query: 'Trastevere Rome streets' },
      { name: 'Fontana di Trevi', tag: 'Icono', query: 'Trevi Fountain Rome' },
    ],
  },
  {
    id: 'praga',
    name: 'Praga',
    country: 'Chequia',
    continent: 'Europa',
    types: ['cultural'],
    priceRange: 'low',
    rating: 4.5,
    description:
      'Torres góticas, callejones empedrados y el Moldava atravesándolo todo. Praga parece diseñada para caminarla de noche, cuando el Puente de Carlos se queda casi vacío.',
    coverQuery: 'Prague Charles Bridge old town',
    coordinates: { lat: 50.0755, lng: 14.4378 },
    language: { code: 'CS', label: 'Checo' },
    highlights: [
      { name: 'Puente de Carlos', tag: 'Monumento', query: 'Charles Bridge Prague' },
      { name: 'Castillo de Praga', tag: 'Castillo', query: 'Prague Castle' },
      { name: 'Reloj Astronómico', tag: 'Icono', query: 'Astronomical Clock Prague' },
    ],
  },
  {
    id: 'amsterdam',
    name: 'Ámsterdam',
    country: 'Países Bajos',
    continent: 'Europa',
    types: ['cultural', 'relax'],
    priceRange: 'high',
    rating: 4.4,
    description:
      'Canales, bicicletas y casas inclinadas que parecen apoyarse unas en otras. Una ciudad compacta donde los museos de primera conviven con mercados flotantes de flores.',
    coverQuery: 'Amsterdam canals houses bikes',
    coordinates: { lat: 52.3676, lng: 4.9041 },
    language: { code: 'NL', label: 'Neerlandés' },
    highlights: [
      { name: 'Museo Van Gogh', tag: 'Museo', query: 'Van Gogh Museum Amsterdam' },
      { name: 'Jordaan', tag: 'Barrio · Canales', query: 'Jordaan Amsterdam canal' },
      { name: 'Vondelpark', tag: 'Parque', query: 'Vondelpark Amsterdam' },
    ],
  },
  {
    id: 'reikiavik',
    name: 'Reikiavik',
    country: 'Islandia',
    continent: 'Europa',
    types: ['aventura', 'relax'],
    priceRange: 'high',
    rating: 4.6,
    description:
      'Puerta de entrada a un país de volcanes, glaciares y auroras boreales. La capital más al norte del mundo combina piscinas geotermales con una escena creativa sorprendente.',
    coverQuery: 'Reykjavik Iceland Hallgrimskirkja',
    coordinates: { lat: 64.1466, lng: -21.9426 },
    language: { code: 'IS', label: 'Islandés' },
    highlights: [
      { name: 'Blue Lagoon', tag: 'Termas', query: 'Blue Lagoon Iceland' },
      { name: 'Círculo Dorado', tag: 'Ruta · Naturaleza', query: 'Golden Circle Iceland Gullfoss' },
      { name: 'Hallgrímskirkja', tag: 'Monumento', query: 'Hallgrimskirkja church Reykjavik' },
    ],
  },
  {
    id: 'atenas',
    name: 'Atenas',
    country: 'Grecia',
    continent: 'Europa',
    types: ['cultural', 'gastro'],
    priceRange: 'low',
    rating: 4.3,
    description:
      'La cuna de la civilización occidental sigue latiendo bajo la Acrópolis. Barrios como Plaka o Monastiraki mezclan ruinas, tabernas y un caos encantador.',
    coverQuery: 'Athens Acropolis Parthenon',
    coordinates: { lat: 37.9838, lng: 23.7275 },
    language: { code: 'EL', label: 'Griego' },
    highlights: [
      { name: 'Acrópolis', tag: 'Monumento', query: 'Acropolis Athens Parthenon' },
      { name: 'Plaka', tag: 'Barrio', query: 'Plaka Athens streets' },
      { name: 'Monastiraki', tag: 'Mercado', query: 'Monastiraki flea market Athens' },
    ],
  },
  {
    id: 'santorini',
    name: 'Santorini',
    country: 'Grecia',
    continent: 'Europa',
    types: ['relax'],
    priceRange: 'high',
    rating: 4.7,
    description:
      'Casas blancas colgadas sobre una caldera volcánica y los atardeceres más fotografiados del Egeo. El destino de postal por excelencia, con calas de arena negra incluidas.',
    coverQuery: 'Santorini Oia blue domes sunset',
    coordinates: { lat: 36.3932, lng: 25.4615 },
    language: { code: 'EL', label: 'Griego' },
    highlights: [
      { name: 'Oia', tag: 'Pueblo · Atardecer', query: 'Oia Santorini sunset' },
      { name: 'Playa Roja', tag: 'Playa', query: 'Red Beach Santorini' },
      { name: 'Fira', tag: 'Capital', query: 'Fira Santorini caldera view' },
    ],
  },
  {
    id: 'estambul',
    name: 'Estambul',
    country: 'Turquía',
    continent: 'Europa',
    types: ['cultural', 'gastro'],
    priceRange: 'low',
    rating: 4.6,
    description:
      'La única ciudad del mundo a caballo entre dos continentes. Mezquitas monumentales, bazares infinitos y el Bósforo como telón de fondo de un choque cultural fascinante.',
    coverQuery: 'Istanbul Hagia Sophia Bosphorus',
    coordinates: { lat: 41.0082, lng: 28.9784 },
    language: { code: 'TR', label: 'Turco' },
    highlights: [
      { name: 'Santa Sofía', tag: 'Monumento', query: 'Hagia Sophia Istanbul' },
      { name: 'Gran Bazar', tag: 'Mercado', query: 'Grand Bazaar Istanbul' },
      { name: 'Mezquita Azul', tag: 'Monumento', query: 'Blue Mosque Istanbul' },
    ],
  },
  // ---------- Asia ----------
  {
    id: 'tokio',
    name: 'Tokio',
    country: 'Japón',
    continent: 'Asia',
    types: ['cultural', 'gastro'],
    priceRange: 'high',
    rating: 4.5,
    description:
      'Neones, templos y la mayor concentración de estrellas Michelin del planeta. Tokio es muchas ciudades a la vez: caótica en Shibuya, serena en Yanaka, futurista en Odaiba.',
    coverQuery: 'Tokyo Shibuya crossing night',
    coordinates: { lat: 35.6762, lng: 139.6503 },
    language: { code: 'JA', label: 'Japonés' },
    highlights: [
      { name: 'Templo Sensō-ji', tag: 'Templo', query: 'Sensoji Temple Asakusa Tokyo' },
      { name: 'Cruce de Shibuya', tag: 'Icono', query: 'Shibuya crossing Tokyo' },
      { name: 'Mercado de Tsukiji', tag: 'Gastronomía', query: 'Tsukiji market Tokyo food' },
    ],
  },
  {
    id: 'kioto',
    name: 'Kioto',
    country: 'Japón',
    continent: 'Asia',
    types: ['cultural', 'relax'],
    priceRange: 'high',
    rating: 4.8,
    description:
      'Mil templos, jardines zen y geishas cruzando callejones de madera. La antigua capital imperial es el Japón que imaginabas antes de ir a Japón.',
    coverQuery: 'Kyoto Fushimi Inari torii gates',
    coordinates: { lat: 35.0116, lng: 135.7681 },
    language: { code: 'JA', label: 'Japonés' },
    featured: true,
    highlights: [
      { name: 'Fushimi Inari', tag: 'Santuario', query: 'Fushimi Inari shrine Kyoto' },
      { name: 'Arashiyama', tag: 'Bosque de bambú', query: 'Arashiyama bamboo forest Kyoto' },
      { name: 'Gion', tag: 'Barrio · Geishas', query: 'Gion district Kyoto' },
    ],
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    continent: 'Asia',
    types: ['relax', 'aventura'],
    priceRange: 'mid',
    rating: 4.7,
    description:
      'Arrozales en terraza, templos entre la jungla y playas para todos los gustos. La isla de los dioses combina espiritualidad, surf y una hospitalidad legendaria.',
    coverQuery: 'Bali rice terraces temple',
    coordinates: { lat: -8.4095, lng: 115.1889 },
    language: { code: 'ID', label: 'Indonesio' },
    highlights: [
      { name: 'Tegalalang', tag: 'Arrozales', query: 'Tegalalang rice terrace Bali' },
      { name: 'Templo Uluwatu', tag: 'Templo · Acantilado', query: 'Uluwatu temple Bali cliff' },
      { name: 'Ubud', tag: 'Pueblo · Jungla', query: 'Ubud Bali jungle' },
    ],
  },
  {
    id: 'bangkok',
    name: 'Bangkok',
    country: 'Tailandia',
    continent: 'Asia',
    types: ['gastro', 'cultural'],
    priceRange: 'low',
    rating: 4.4,
    description:
      'Templos dorados, mercados flotantes y la mejor comida callejera del mundo. Bangkok abruma al principio y engancha después: es puro movimiento.',
    coverQuery: 'Bangkok Wat Arun temple',
    coordinates: { lat: 13.7563, lng: 100.5018 },
    language: { code: 'TH', label: 'Tailandés' },
    highlights: [
      { name: 'Gran Palacio', tag: 'Monumento', query: 'Grand Palace Bangkok' },
      { name: 'Wat Arun', tag: 'Templo', query: 'Wat Arun temple Bangkok' },
      { name: 'Chatuchak', tag: 'Mercado', query: 'Chatuchak market Bangkok' },
    ],
  },
  {
    id: 'hanoi',
    name: 'Hanói',
    country: 'Vietnam',
    continent: 'Asia',
    types: ['cultural', 'gastro'],
    priceRange: 'low',
    rating: 4.3,
    description:
      'Motos por miles, pho humeante en cada esquina y un casco antiguo de 36 calles gremiales. La puerta de entrada perfecta a la bahía de Halong.',
    coverQuery: 'Hanoi Vietnam old quarter street',
    coordinates: { lat: 21.0285, lng: 105.8542 },
    language: { code: 'VI', label: 'Vietnamita' },
    highlights: [
      { name: 'Old Quarter', tag: 'Barrio', query: 'Hanoi old quarter' },
      { name: 'Bahía de Halong', tag: 'Excursión · Naturaleza', query: 'Halong Bay Vietnam' },
      { name: 'Train Street', tag: 'Icono', query: 'Hanoi train street' },
    ],
  },
  {
    id: 'seul',
    name: 'Seúl',
    country: 'Corea del Sur',
    continent: 'Asia',
    types: ['cultural', 'gastro'],
    priceRange: 'mid',
    rating: 4.5,
    description:
      'Palacios de la dinastía Joseon junto a rascacielos y barrios de moda que marcan tendencia mundial. El K-everything tiene su capital aquí, y se come de maravilla.',
    coverQuery: 'Seoul Gyeongbokgung palace skyline',
    coordinates: { lat: 37.5665, lng: 126.978 },
    language: { code: 'KO', label: 'Coreano' },
    highlights: [
      { name: 'Gyeongbokgung', tag: 'Palacio', query: 'Gyeongbokgung palace Seoul' },
      { name: 'Bukchon Hanok', tag: 'Barrio tradicional', query: 'Bukchon Hanok village Seoul' },
      { name: 'Myeongdong', tag: 'Compras · Street food', query: 'Myeongdong Seoul street food' },
    ],
  },
  {
    id: 'singapur',
    name: 'Singapur',
    country: 'Singapur',
    continent: 'Asia',
    types: ['gastro', 'relax'],
    priceRange: 'high',
    rating: 4.4,
    description:
      'La ciudad-jardín donde la comida de hawker vale una estrella Michelin. Futurista, verde e impecable: el escenario de Gardens by the Bay parece de otro planeta.',
    coverQuery: 'Singapore Marina Bay Gardens',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    language: { code: 'EN', label: 'Inglés' },
    highlights: [
      {
        name: 'Gardens by the Bay',
        tag: 'Parque · Futurista',
        query: 'Gardens by the Bay Singapore',
      },
      { name: 'Marina Bay Sands', tag: 'Icono', query: 'Marina Bay Sands Singapore' },
      { name: 'Hawker Centers', tag: 'Gastronomía', query: 'Singapore hawker center food' },
    ],
  },
  {
    id: 'dubai',
    name: 'Dubái',
    country: 'Emiratos Árabes',
    continent: 'Asia',
    types: ['relax', 'aventura'],
    priceRange: 'high',
    rating: 4.2,
    description:
      'Rascacielos imposibles levantados sobre el desierto. Entre el zoco del oro y el edificio más alto del mundo, Dubái es exceso puro — y safaris de dunas al atardecer.',
    coverQuery: 'Dubai Burj Khalifa skyline desert',
    coordinates: { lat: 25.2048, lng: 55.2708 },
    language: { code: 'AR', label: 'Árabe' },
    highlights: [
      { name: 'Burj Khalifa', tag: 'Icono', query: 'Burj Khalifa Dubai' },
      { name: 'Desierto', tag: 'Safari · Dunas', query: 'Dubai desert safari dunes' },
      { name: 'Zoco del Oro', tag: 'Mercado', query: 'Gold Souk Dubai' },
    ],
  },
  // ---------- América ----------
  {
    id: 'nueva-york',
    name: 'Nueva York',
    country: 'EEUU',
    continent: 'América',
    types: ['cultural', 'gastro'],
    priceRange: 'high',
    rating: 4.2,
    description:
      'La ciudad que nunca duerme cumple todos los tópicos y aun así sorprende. Museos gigantes, barrios con personalidad propia y una energía que no existe en ningún otro sitio.',
    coverQuery: 'New York Manhattan skyline',
    coordinates: { lat: 40.7128, lng: -74.006 },
    language: { code: 'EN', label: 'Inglés' },
    highlights: [
      { name: 'Central Park', tag: 'Parque', query: 'Central Park New York aerial' },
      { name: 'Brooklyn Bridge', tag: 'Icono', query: 'Brooklyn Bridge New York' },
      { name: 'The Met', tag: 'Museo', query: 'Metropolitan Museum New York' },
    ],
  },
  {
    id: 'cusco',
    name: 'Cusco',
    country: 'Perú',
    continent: 'América',
    types: ['cultural', 'aventura'],
    priceRange: 'low',
    rating: 4.8,
    description:
      'La antigua capital del imperio inca, a 3.400 metros de altura, es la base para llegar a Machu Picchu. Muros incas, iglesias coloniales y el Valle Sagrado a un paso.',
    coverQuery: 'Cusco Peru plaza de armas',
    coordinates: { lat: -13.5319, lng: -71.9675 },
    language: { code: 'ES', label: 'Español' },
    featured: true,
    highlights: [
      { name: 'Machu Picchu', tag: 'Maravilla', query: 'Machu Picchu Peru' },
      { name: 'Valle Sagrado', tag: 'Ruta · Naturaleza', query: 'Sacred Valley Peru' },
      { name: 'San Blas', tag: 'Barrio', query: 'San Blas Cusco' },
    ],
  },
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    continent: 'América',
    types: ['cultural', 'gastro'],
    priceRange: 'low',
    rating: 4.5,
    description:
      'Tango, parrillas y librerías en teatros centenarios. La ciudad más europea de Sudamérica tiene barrios que son mundos: San Telmo, Palermo, La Boca.',
    coverQuery: 'Buenos Aires La Boca Caminito',
    coordinates: { lat: -34.6037, lng: -58.3816 },
    language: { code: 'ES', label: 'Español' },
    highlights: [
      { name: 'Caminito', tag: 'Barrio · La Boca', query: 'Caminito La Boca Buenos Aires' },
      { name: 'Recoleta', tag: 'Cementerio · Historia', query: 'Recoleta cemetery Buenos Aires' },
      { name: 'San Telmo', tag: 'Mercado · Tango', query: 'San Telmo market Buenos Aires' },
    ],
  },
  {
    id: 'rio',
    name: 'Río de Janeiro',
    country: 'Brasil',
    continent: 'América',
    types: ['relax', 'aventura'],
    priceRange: 'mid',
    rating: 4.6,
    description:
      'Montañas de granito cayendo sobre playas míticas, samba en la calle y el Cristo vigilándolo todo. Pocas ciudades tienen un escenario natural así.',
    coverQuery: 'Rio de Janeiro Christ Redeemer aerial',
    coordinates: { lat: -22.9068, lng: -43.1729 },
    language: { code: 'PT', label: 'Portugués' },
    highlights: [
      { name: 'Cristo Redentor', tag: 'Icono', query: 'Christ the Redeemer Rio' },
      { name: 'Pan de Azúcar', tag: 'Mirador', query: 'Sugarloaf mountain Rio' },
      { name: 'Ipanema', tag: 'Playa', query: 'Ipanema beach Rio de Janeiro' },
    ],
  },
  {
    id: 'cdmx',
    name: 'Ciudad de México',
    country: 'México',
    continent: 'América',
    types: ['cultural', 'gastro'],
    priceRange: 'low',
    rating: 4.5,
    description:
      'Una megalópolis construida sobre una ciudad azteca, con la escena gastronómica más excitante de América. Murales, mercados y barrios como Roma o Coyoacán para perderse.',
    coverQuery: 'Mexico City Palacio Bellas Artes',
    coordinates: { lat: 19.4326, lng: -99.1332 },
    language: { code: 'ES', label: 'Español' },
    highlights: [
      { name: 'Teotihuacán', tag: 'Ruinas', query: 'Teotihuacan pyramids Mexico' },
      { name: 'Coyoacán', tag: 'Barrio · Frida', query: 'Coyoacan Mexico City colorful' },
      { name: 'Bellas Artes', tag: 'Monumento', query: 'Palacio Bellas Artes Mexico City' },
    ],
  },
  {
    id: 'vancouver',
    name: 'Vancouver',
    country: 'Canadá',
    continent: 'América',
    types: ['aventura', 'relax'],
    priceRange: 'high',
    rating: 4.3,
    description:
      'Océano por un lado, montañas nevadas por el otro. Vancouver es la excusa urbana perfecta para una escapada de naturaleza: kayak al amanecer, esquí por la tarde.',
    coverQuery: 'Vancouver Canada skyline mountains',
    coordinates: { lat: 49.2827, lng: -123.1207 },
    language: { code: 'EN', label: 'Inglés' },
    highlights: [
      { name: 'Stanley Park', tag: 'Parque', query: 'Stanley Park Vancouver seawall' },
      { name: 'Granville Island', tag: 'Mercado', query: 'Granville Island Vancouver' },
      { name: 'Capilano', tag: 'Puente colgante', query: 'Capilano suspension bridge' },
    ],
  },
  {
    id: 'la-habana',
    name: 'La Habana',
    country: 'Cuba',
    continent: 'América',
    types: ['cultural', 'relax'],
    priceRange: 'low',
    rating: 4.1,
    description:
      'Coches clásicos, fachadas coloniales desgastadas por el salitre y son cubano saliendo de cada ventana. Una ciudad detenida en el tiempo que se vive con todos los sentidos.',
    coverQuery: 'Havana Cuba classic cars colonial',
    coordinates: { lat: 23.1136, lng: -82.3666 },
    language: { code: 'ES', label: 'Español' },
    highlights: [
      { name: 'Habana Vieja', tag: 'Casco histórico', query: 'Old Havana streets' },
      { name: 'El Malecón', tag: 'Paseo', query: 'Malecon Havana sunset' },
      { name: 'Viñales', tag: 'Excursión · Valle', query: 'Vinales valley Cuba' },
    ],
  },
  // ---------- África ----------
  {
    id: 'marrakech',
    name: 'Marrakech',
    country: 'Marruecos',
    continent: 'África',
    types: ['cultural', 'gastro'],
    priceRange: 'low',
    rating: 4.4,
    description:
      'Zocos laberínticos, riads escondidos tras puertas anónimas y la plaza de Jemaa el-Fna convertida en teatro cada atardecer. El desierto y el Atlas esperan a las puertas.',
    coverQuery: 'Marrakech Morocco medina souk',
    coordinates: { lat: 31.6295, lng: -7.9811 },
    language: { code: 'AR', label: 'Árabe' },
    featured: true,
    highlights: [
      { name: 'Jemaa el-Fna', tag: 'Plaza · Icono', query: 'Jemaa el-Fna square Marrakech' },
      { name: 'Jardín Majorelle', tag: 'Jardín', query: 'Majorelle Garden Marrakech blue' },
      { name: 'La Medina', tag: 'Zoco', query: 'Marrakech medina souk spices' },
    ],
  },
  {
    id: 'el-cairo',
    name: 'El Cairo',
    country: 'Egipto',
    continent: 'África',
    types: ['cultural'],
    priceRange: 'low',
    rating: 4.3,
    description:
      'Las pirámides de Giza a las afueras, cinco mil años de historia dentro. Caótico, ruidoso y absolutamente fascinante: el Nilo lo atraviesa todo.',
    coverQuery: 'Cairo Egypt pyramids Giza',
    coordinates: { lat: 30.0444, lng: 31.2357 },
    language: { code: 'AR', label: 'Árabe' },
    highlights: [
      { name: 'Pirámides de Giza', tag: 'Maravilla', query: 'Giza pyramids Egypt' },
      { name: 'Museo Egipcio', tag: 'Museo', query: 'Egyptian Museum Cairo' },
      { name: 'Khan el-Khalili', tag: 'Bazar', query: 'Khan el-Khalili bazaar Cairo' },
    ],
  },
  {
    id: 'ciudad-del-cabo',
    name: 'Ciudad del Cabo',
    country: 'Sudáfrica',
    continent: 'África',
    types: ['aventura', 'relax'],
    priceRange: 'mid',
    rating: 4.7,
    description:
      'Table Mountain de fondo, pingüinos en la playa y viñedos a media hora. Pocas ciudades ofrecen tanta naturaleza espectacular sin salir del área metropolitana.',
    coverQuery: 'Cape Town Table Mountain aerial',
    coordinates: { lat: -33.9249, lng: 18.4241 },
    language: { code: 'EN', label: 'Inglés' },
    highlights: [
      { name: 'Table Mountain', tag: 'Montaña', query: 'Table Mountain Cape Town' },
      { name: 'Boulders Beach', tag: 'Playa · Pingüinos', query: 'Boulders Beach penguins' },
      { name: 'Cabo de Buena Esperanza', tag: 'Excursión', query: 'Cape of Good Hope' },
    ],
  },
  // ---------- Oceanía ----------
  {
    id: 'sidney',
    name: 'Sídney',
    country: 'Australia',
    continent: 'Oceanía',
    types: ['relax', 'aventura'],
    priceRange: 'high',
    rating: 4.5,
    description:
      'La Ópera, el puente y decenas de playas urbanas donde el surf es religión. Sídney vive de cara al mar y contagia su estilo de vida al aire libre desde el primer día.',
    coverQuery: 'Sydney Opera House harbour',
    coordinates: { lat: -33.8688, lng: 151.2093 },
    language: { code: 'EN', label: 'Inglés' },
    featured: true,
    highlights: [
      { name: 'Opera House', tag: 'Icono', query: 'Sydney Opera House' },
      { name: 'Bondi Beach', tag: 'Playa · Surf', query: 'Bondi Beach Sydney' },
      { name: 'Blue Mountains', tag: 'Excursión · Naturaleza', query: 'Blue Mountains Australia' },
    ],
  },
  {
    id: 'auckland',
    name: 'Auckland',
    country: 'Nueva Zelanda',
    continent: 'Oceanía',
    types: ['aventura'],
    priceRange: 'high',
    rating: 4.2,
    description:
      'La ciudad de las velas es la base perfecta para explorar la Tierra Media real: volcanes, playas negras y fiordos. Aventura en estado puro a un vuelo interno de distancia.',
    coverQuery: 'Auckland New Zealand skyline harbour',
    coordinates: { lat: -36.8509, lng: 174.7645 },
    language: { code: 'EN', label: 'Inglés' },
    highlights: [
      { name: 'Isla Waiheke', tag: 'Isla · Viñedos', query: 'Waiheke Island New Zealand' },
      { name: 'Piha Beach', tag: 'Playa negra', query: 'Piha Beach black sand' },
      { name: 'Hobbiton', tag: 'Excursión', query: 'Hobbiton New Zealand' },
    ],
  },
];

export function getDestination(id: string): Destination | undefined {
  return DESTINATIONS.find((d) => d.id === id);
}
